#pragma once

// from glfw3.h
#define DOTENGINE_MOUSE_BUTTON_1         0
#define DOTENGINE_MOUSE_BUTTON_2         1
#define DOTENGINE_MOUSE_BUTTON_3         2
#define DOTENGINE_MOUSE_BUTTON_4         3
#define DOTENGINE_MOUSE_BUTTON_5         4
#define DOTENGINE_MOUSE_BUTTON_6         5
#define DOTENGINE_MOUSE_BUTTON_7         6
#define DOTENGINE_MOUSE_BUTTON_8         7
#define DOTENGINE_MOUSE_BUTTON_LAST      DOTENGINE_MOUSE_BUTTON_8
#define DOTENGINE_MOUSE_BUTTON_LEFT      DOTENGINE_MOUSE_BUTTON_1
#define DOTENGINE_MOUSE_BUTTON_RIGHT     DOTENGINE_MOUSE_BUTTON_2
#define DOTENGINE_MOUSE_BUTTON_MIDDLE    DOTENGINE_MOUSE_BUTTON_3